"""empty message

Revision ID: 35067656dd11
Revises: 1f836a0a8f7a
Create Date: 2022-12-29 00:48:51.302217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35067656dd11'
down_revision = '1f836a0a8f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
